blank_issues_enabled: true
contact_links:
  - name: ğŸ“– README
    url: https://github.com/pablosalgado/budget-buddy/blob/main/README.md
    about: Project documentation
  - name: ğŸ“‹ Guidelines
    url: https://github.com/pablosalgado/budget-buddy/tree/main/.github/instructions
    about: Coding standards
